/*
---------------------------------------------------------
 English Explorer – v3 Dataset
 Part 1: Grammar & Vocabulary  (Block 1 of 2)
 Structure:
   grammar_easy, grammar_average
---------------------------------------------------------
*/
const questionBankPart1 = {
  grammar_easy: [
    { q: "She _____ to school every day.", opts:["go","goes","going"], ans:"goes" },
    { q: "They _____ playing football now.", opts:["is","are","was"], ans:"are" },
    { q: "He didn’t _____ his homework.", opts:["do","does","did"], ans:"do" },
    { q: "We _____ dinner at seven o’clock yesterday.", opts:["have","had","has"], ans:"had" },
    { q: "The cat _____ under the chair.", opts:["is","are","was"], ans:"is" },
    { q: "I _____ a pencil in my bag.", opts:["has","have","had"], ans:"have" },
    { q: "The boy _____ his shoes before running.", opts:["tie","ties","tied"], ans:"tied" },
    { q: "There _____ many stars in the sky.", opts:["is","are","was"], ans:"are" },
    { q: "She _____ already finished her project.", opts:["have","has","had"], ans:"has" },
    { q: "My parents _____ watching television.", opts:["is","are","was"], ans:"are" },
    { q: "The children _____ excited about the trip.", opts:["is","are","was"], ans:"are" },
    { q: "We _____ going to the library today.", opts:["is","are","am"], ans:"are" },
    { q: "The sun _____ in the east.", opts:["rise","rises","rising"], ans:"rises" },
    { q: "I _____ never seen snow before.", opts:["has","have","had"], ans:"have" },
    { q: "She _____ a beautiful dress yesterday.", opts:["wear","wears","wore"], ans:"wore" },
    { q: "Tom _____ to play the piano after dinner.", opts:["like","likes","liked"], ans:"likes" },
    { q: "The dogs _____ barking loudly.", opts:["is","are","was"], ans:"are" },
    { q: "It _____ raining when I left home.", opts:["is","was","were"], ans:"was" },
    { q: "We _____ the museum last Sunday.", opts:["visit","visited","visiting"], ans:"visited" },
    { q: "The teacher _____ a story to us.", opts:["tell","tells","told"], ans:"told" },
    { q: "The flowers _____ lovely.", opts:["smell","smells","smelled"], ans:"smell" },
    { q: "Each student _____ a worksheet.", opts:["have","has","having"], ans:"has" },
    { q: "She _____ her homework before dinner.", opts:["finish","finishes","finished"], ans:"finished" },
    { q: "There _____ a lot of milk in the jug.", opts:["are","is","were"], ans:"is" },
    { q: "He _____ up early every morning.", opts:["get","gets","got"], ans:"gets" },
    { q: "We _____ to the beach last weekend.", opts:["go","went","going"], ans:"went" },
    { q: "They _____ reading a new storybook.", opts:["is","are","was"], ans:"are" },
    { q: "My brother _____ football very well.", opts:["play","plays","played"], ans:"plays" },
    { q: "The children _____ happy to see the clown.", opts:["was","were","is"], ans:"were" },
    { q: "She _____ cooking when her friend arrived.", opts:["was","were","is"], ans:"was" }
  ],

  grammar_average: [
    { q: "If I _____ time, I would help you.", opts:["have","had","has"], ans:"had" },
    { q: "She speaks as if she _____ everything.", opts:["know","knew","knows"], ans:"knew" },
    { q: "Neither the teacher nor the students _____ present.", opts:["was","were","are"], ans:"were" },
    { q: "Everybody _____ welcome to join the event.", opts:["are","is","were"], ans:"is" },
    { q: "The ducks _____ swimming in the pond.", opts:["is","are","was"], ans:"are" },
    { q: "Each of the boys _____ done his work.", opts:["have","has","had"], ans:"has" },
    { q: "She prefers tea _____ coffee.", opts:["than","to","over"], ans:"to" },
    { q: "They have been waiting _____ an hour.", opts:["since","for","from"], ans:"for" },
    { q: "Please give the keys to _____.", opts:["he","him","his"], ans:"him" },
    { q: "Neither of the answers _____ correct.", opts:["are","is","were"], ans:"is" },
    { q: "The students were tired, _____ they continued working.", opts:["so","but","because"], ans:"but" },
    { q: "I will go for a walk _____ it stops raining.", opts:["if","because","so"], ans:"if" },
    { q: "She bought apples _____ oranges at the market.", opts:["and","or","but"], ans:"and" },
    { q: "We stayed at home _____ it was raining.", opts:["because","so","but"], ans:"because" },
    { q: "He runs _____ than his brother.", opts:["fast","faster","fastest"], ans:"faster" },
    { q: "This is the _____ movie I have ever seen.", opts:["funny","funnier","funniest"], ans:"funniest" },
    { q: "Either my mother or my sisters _____ cooking now.", opts:["is","are","was"], ans:"are" },
    { q: "Both of the girls _____ good at dancing.", opts:["is","are","was"], ans:"are" },
    { q: "The news _____ surprising to everyone.", opts:["is","are","were"], ans:"is" },
    { q: "The book on the table _____ mine.", opts:["is","are","were"], ans:"is" },
    { q: "He behaves as though he _____ the boss.", opts:["is","was","were"], ans:"were" },
    { q: "If she _____ earlier, she would catch the bus.", opts:["leave","left","leaves"], ans:"left" },
    { q: "The man _____ the gate is my uncle.", opts:["who","which","where"], ans:"who" },
    { q: "The teacher asked us _____ we had finished the task.", opts:["what","if","that"], ans:"if" },
    { q: "I am not sure _____ he will come.", opts:["if","that","who"], ans:"if" },
    { q: "The child cried because she _____ her toy.", opts:["lost","lose","loses"], ans:"lost" },
    { q: "You may go home after you _____ your work.", opts:["finish","finished","finishes"], ans:"finish" },
    { q: "The bus usually _____ at this stop.", opts:["stop","stops","stopped"], ans:"stops" },
    { q: "She sings _____ than her friend.", opts:["beautiful","more beautifully","most beautiful"], ans:"more beautifully" },
    { q: "My uncle has lived here _____ five years.", opts:["for","since","from"], ans:"for" }
  ],
    grammar_difficult: [
    { q: "Hardly _____ he reached the station when the train left.", opts:["had","has","have"], ans:"had" },
    { q: "No sooner had the bell rung _____ the students ran out.", opts:["than","when","then"], ans:"than" },
    { q: "If I _____ you, I would apologize.", opts:["am","was","were"], ans:"were" },
    { q: "By the time we arrived, the movie _____.", opts:["started","has started","had started"], ans:"had started" },
    { q: "Neither of them _____ able to answer the question.", opts:["was","were","are"], ans:"was" },
    { q: "The book, together with the notes, _____ on the table.", opts:["is","are","were"], ans:"is" },
    { q: "He behaves as if he _____ everything.", opts:["knows","knew","had known"], ans:"knew" },
    { q: "I wish I _____ more careful yesterday.", opts:["am","was","had been"], ans:"had been" },
    { q: "Each of the players _____ given a medal.", opts:["were","was","are"], ans:"was" },
    { q: "Had I known your address, I _____ written to you.", opts:["would have","will have","had"], ans:"would have" },
    { q: "Not only you but also she _____ responsible.", opts:["is","are","were"], ans:"is" },
    { q: "It’s high time you _____ your homework.", opts:["do","did","have done"], ans:"did" },
    { q: "If he had studied harder, he _____ the test.", opts:["will pass","would have passed","passed"], ans:"would have passed" },
    { q: "The teacher insisted that he _____ the truth.", opts:["tells","tell","told"], ans:"tell" },
    { q: "No one knew where the cat _____.", opts:["has gone","had gone","goes"], ans:"had gone" },
    { q: "He speaks as though he _____ in charge.", opts:["is","were","was"], ans:"were" },
    { q: "I met the woman _____ helped me find my bag.", opts:["which","who","whom"], ans:"who" },
    { q: "The longer he waited, the _____ he became.", opts:["angry","angrier","more angry"], ans:"angrier" },
    { q: "Had it not been for the rain, we _____ gone out.", opts:["will have","would have","had"], ans:"would have" },
    { q: "He looked as if he _____ crying.", opts:["has been","had been","was"], ans:"had been" }
  ],

  vocabulary_easy: [
    { q: "Opposite of ‘happy’?", opts:["sad","joyful","angry"], ans:"sad" },
    { q: "Opposite of ‘big’?", opts:["small","tall","long"], ans:"small" },
    { q: "Synonym of ‘fast’?", opts:["quick","slow","lazy"], ans:"quick" },
    { q: "Synonym of ‘clever’?", opts:["smart","dull","lazy"], ans:"smart" },
    { q: "Opposite of ‘hot’?", opts:["cold","warm","wet"], ans:"cold" },
    { q: "Opposite of ‘old’?", opts:["young","ancient","long"], ans:"young" },
    { q: "‘Glimpse’ means:", opts:["a quick look","a long stare","a bright light"], ans:"a quick look" },
    { q: "‘Purchase’ means:", opts:["to buy","to sell","to borrow"], ans:"to buy" },
    { q: "‘Gigantic’ means:", opts:["huge","tiny","average"], ans:"huge" },
    { q: "‘Polite’ means:", opts:["rude","kind","loud"], ans:"kind" },
    { q: "‘Drenched’ means:", opts:["dry","soaked","dirty"], ans:"soaked" },
    { q: "‘Brave’ means:", opts:["cowardly","fearless","weak"], ans:"fearless" },
    { q: "Opposite of ‘short’?", opts:["long","tall","low"], ans:"long" },
    { q: "Synonym of ‘hungry’?", opts:["tired","starving","sleepy"], ans:"starving" },
    { q: "‘Tiny’ means:", opts:["very small","very big","tall"], ans:"very small" },
    { q: "‘Enormous’ means:", opts:["huge","tiny","light"], ans:"huge" },
    { q: "‘Quickly’ means:", opts:["slowly","fast","softly"], ans:"fast" },
    { q: "‘Delicious’ means:", opts:["tasty","ugly","boring"], ans:"tasty" },
    { q: "‘Silent’ means:", opts:["quiet","noisy","peaceful"], ans:"quiet" },
    { q: "‘Ancient’ means:", opts:["very old","modern","new"], ans:"very old" }
  ],

  vocabulary_average: [
    { q: "Synonym of ‘brilliant’?", opts:["dull","bright","weak"], ans:"bright" },
    { q: "Opposite of ‘success’?", opts:["failure","achievement","luck"], ans:"failure" },
    { q: "‘Exhausted’ means:", opts:["very tired","very excited","very sad"], ans:"very tired" },
    { q: "‘Content’ means:", opts:["happy","angry","sleepy"], ans:"happy" },
    { q: "‘Eager’ means:", opts:["interested","lazy","sleepy"], ans:"interested" },
    { q: "‘Fragile’ means:", opts:["strong","breakable","heavy"], ans:"breakable" },
    { q: "‘Weary’ means:", opts:["tired","energetic","angry"], ans:"tired" },
    { q: "Opposite of ‘victory’?", opts:["defeat","win","fight"], ans:"defeat" },
    { q: "‘Furious’ means:", opts:["angry","happy","sad"], ans:"angry" },
    { q: "‘Grateful’ means:", opts:["thankful","angry","sad"], ans:"thankful" },
    { q: "‘Miserable’ means:", opts:["very sad","very happy","very tired"], ans:"very sad" },
    { q: "‘Envy’ means:", opts:["jealousy","happiness","surprise"], ans:"jealousy" },
    { q: "‘Humble’ means:", opts:["proud","modest","rude"], ans:"modest" },
    { q: "‘Cautious’ means:", opts:["careful","careless","rude"], ans:"careful" },
    { q: "‘Generous’ means:", opts:["kind","selfish","greedy"], ans:"kind" },
    { q: "‘Timid’ means:", opts:["shy","bold","loud"], ans:"shy" },
    { q: "‘Swift’ means:", opts:["quick","slow","steady"], ans:"quick" },
    { q: "‘Adore’ means:", opts:["hate","love","ignore"], ans:"love" },
    { q: "‘Fragile’ opposite is:", opts:["strong","weak","breakable"], ans:"strong" },
    { q: "‘Tranquil’ means:", opts:["peaceful","noisy","stormy"], ans:"peaceful" }
  ],

  vocabulary_difficult: [
    { q: "‘Meticulous’ means:", opts:["careless","precise","hurried"], ans:"precise" },
    { q: "‘Benevolent’ means:", opts:["kind","selfish","lazy"], ans:"kind" },
    { q: "‘Tedious’ means:", opts:["boring","exciting","short"], ans:"boring" },
    { q: "‘Reluctant’ means:", opts:["unwilling","eager","brave"], ans:"unwilling" },
    { q: "‘Vast’ means:", opts:["huge","tiny","narrow"], ans:"huge" },
    { q: "‘Innovative’ means:", opts:["creative","lazy","boring"], ans:"creative" },
    { q: "‘Persevere’ means:", opts:["give up","keep trying","rest"], ans:"keep trying" },
    { q: "‘Elated’ means:", opts:["very happy","very sad","angry"], ans:"very happy" },
    { q: "‘Ponder’ means:", opts:["think deeply","walk fast","sleep"], ans:"think deeply" },
    { q: "‘Generosity’ means:", opts:["kindness","anger","jealousy"], ans:"kindness" },
    { q: "‘Vivid’ means:", opts:["bright","dark","pale"], ans:"bright" },
    { q: "‘Sincere’ means:", opts:["honest","dishonest","lazy"], ans:"honest" },
    { q: "‘Reluctance’ means:", opts:["unwillingness","happiness","sadness"], ans:"unwillingness" },
    { q: "‘Courageous’ means:", opts:["brave","cowardly","afraid"], ans:"brave" },
    { q: "‘Endure’ means:", opts:["to suffer patiently","to avoid","to enjoy"], ans:"to suffer patiently" },
    { q: "‘Gracious’ means:", opts:["polite","rude","lazy"], ans:"polite" },
    { q: "‘Oblivious’ means:", opts:["unaware","careful","thoughtful"], ans:"unaware" },
    { q: "‘Diligent’ means:", opts:["hardworking","lazy","sleepy"], ans:"hardworking" },
    { q: "‘Compassionate’ means:", opts:["kind and caring","selfish","rude"], ans:"kind and caring" },
    { q: "‘Ambitious’ means:", opts:["determined to succeed","lazy","unsure"], ans:"determined to succeed" }
  ]
};
  